# Generated by Django 5.2.6 on 2026-07-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(verbose_name=100)),
                ("age", models.IntegerField(default=18)),
                ("email", models.CharField(unique=True, verbose_name=100)),
            ],
        ),
    ]
