# Generated by Django 6.0.7 on 2026-08-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                ("age", models.IntegerField()),
                ("email", models.EmailField(max_length=150, unique=True)),
            ],
        ),
    ]
