# Generated by Django 6.0.7 on 2026-07-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(verbose_name=255)),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name=15),
                ),
                ("mobile", models.CharField(max_length=10)),
            ],
        ),
    ]
