# Generated by Django 6.0.7 on 2026-07-30 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Students",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, null=True)),
                (
                    "age",
                    models.CharField(
                        validators=[
                            django.core.validators.MinValueValidator(18),
                            django.core.validators.MaxValueValidator(50),
                        ]
                    ),
                ),
                ("email", models.EmailField(max_length=100)),
            ],
        ),
    ]
