# Generated by Django 6.0.7 on 2026-07-29 06:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Students",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(verbose_name=100)),
                (
                    "age",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ]
                    ),
                ),
                ("email", models.CharField(unique=True, verbose_name=50)),
                ("mobile", models.CharField(unique=True, verbose_name=50)),
            ],
        ),
    ]
